### ISSUE TITLE
Hear myself

### ISSUE THREAD

**Issue by Chopan22** [pierr3/TrackAudio#119]
Implement a way to hear myself (make an output) with radio effects.

Honestly I know this is probably not the idea of the software and a crazy and weird idea, so I would understand if it's not possible.

**Comment by williammck** [comment]
While real world aviation headsets/radios do have sidetone, it's not going to have any sort of traditional radio effect, as it's not going over the airwaves.
Since the VATSIM audio servers, like real world radios, degrade transmissions depending on distance, what you'd hear locally wouldn't be representative of how you're heard by others.
I don't think it's realistic for those reasons. You can configure sidetone in your OS, but it's likely not in the cards to provide a separate output for this.

**Comment by pierr3** [comment]
Agree with @williammck - check your OS settings, it should be enough
