### ISSUE TITLE
Positions with long names do not fit into the transceiver window

### ISSUE THREAD

**Issue by VATNZ-MR** [pierr3/TrackAudio#180]
Our sectors have quite long names in New Zealand, typically 2 characters more than usual, such as `NZCH-T_CTR` instead of just `NZAA_CTR` and these names do not currently fit on the transceiver buttons within TrackAudio

![image](https://github.com/user-attachments/assets/dbad9c16-aace-4660-9273-b2959a96860f)

Version 1.3.0 beta2

**Comment by capzDE** [comment]
I agree that logins/position names that have 12 characters (the current limit) don't fit into the box entirely; with 11 characters, however, the boxes are wide enough. A slight increase to the width should resolve the length issue.
The fact that your login/position name middle parts and suffixes are largely hidden behind the XC(A) and SPK buttons appears to be caused by using a dash instead of an underscore, which the software probably interprets as an appropriate place to separate a word across two lines (just like Word and similar programs do) - we are using underscores and the logins/position names remain on one line. Maybe something could be changed here to ensure the logins/position names are always on one and the same line.

I have attached a screenshot with a couple of the positions in Germany as an example for both points.
![image](https://github.com/user-attachments/assets/7fac46d7-78bf-4e0f-b97c-f36a5146736e)

**Comment by pierr3** [comment]
Good catch, it’s the “-“ character which I never tested, i’ll increase the
box size by a couple pixels.
